force_auth = false

credentials = [
    {usr="root", pwd="***"},
    {usr="bf", pwd="***"},
    {usr="ci", pwd="***"},
    {usr="ma", pwd="***"},
    {usr="sn", pwd="***"}
]

usr_projects = [
    {usr="root", projects="*"},
    {usr="bf", projects="bf-co-era5_land;bf-hb-era5_land"},
    {usr="ci", projects="ci-c-era5_land;ci-s-era5_land"},
    {usr="ma", projects="ma-tt-era5_land"},
    {usr="sn", projects="sn-ko-era5_land;sn-se-era5_land;sn-ta-era5_land;sn-study-era5_land,sn-study-enacts"}
]

project_path = [
    {project="context", path="./data/"},
    {project="bf-co-era5_land", path="./data/"},
    {project="bf-hb-era5_land", path="./data/"},
    {project="ci-c-era5_land", path="./data/"},
    {project="ci-s-era5_land", path="./data/"},
    {project="ma-tt-era5_land", path="./data/"},
    {project="sn-ko-era5_land", path="./data/"},
    {project="sn-se-era5_land", path="./data/"},
    {project="sn-ta-era5_land", path="./data/"},
    {project="sn-study-era5_land", path="./data/"},
    {project="sn-study-enacts", path="./data/"}
]

[gd]
json = "gd.json"
client_id = "***"
client_secret = "***"
refresh_token = "***"
auth_url = "https://oauth2.googleapis.com/token"
auth_uri = "https://developers.google.com/oauthplayground"
api_url = "https://www.googleapis.com/drive/v3/files/"
scopes = ["https://www.googleapis.com/auth/drive"]